### ISSUE TITLE
box does not include p9 module

### ISSUE THREAD

**Issue by muelli** [geerlingguy/packer-centos-6#6]
It's be nice to be able to use the box with libvirt. The file sharing mode of choice with libvirt is p9fs. However, it seems that modules are missing.  It'd be cool if the centos box includes the modules.

**Comment by geerlingguy** [comment]
Since this is a little less common use case than something like Rsync, I'd rather leave it to downstream users of the box to install it (rather than require every one of the thousands of downloads per month to use an extra 20+ MB of bandwidth for something they'll never use).

It's the same with something like NFS or guest additions—I'd rather let provisioners add in things like this via Vagrant/shell scripts/Ansible/etc.

**Comment by muelli** [comment]
I mostly agree. The problem is, though, that the vagrant doesn't fully start the box, because mounting the shared folder failed.  I obviously don't know, but I can imagine libvirt users to regularly make use of p9fs. So maybe it's possible to only have the p9 modules for the libvirt provider.
